name: CD
on:
  push:
    branches:
      - master
jobs:
  build:
    name: "Install/Pre-Deploy/Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn
        name: Install root package dependencies
      - run: yarn bootstrap
        name: Install inner package dependencies
      - run: yarn deploy:ci --token=$FIREBASE_TOKEN
        name: Deploy inner packages code
        env:
          super_secret: ${{ secrets.FIREBASE_TOKEN }}
