name: CI
on:
  push:
    branches-ignore:
      - master
jobs:
  install-dependencies:
    name: "Install >"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        script: ['lint', 'format', 'build', 'test:ci']
    steps:
      - uses: actions/checkout@v2
        name: Checkout the code
      - uses: actions/setup-node@v1
        name: Setup node v10.x environment
        with:
          node-version: '10.x'
      - uses: actions/cache@master
        name: Restore lerna-style dependencies
        id: lerna_cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
        name: Install root package dependencies
        if: steps.lerna_cache.outputs.cache-hit != 'true'
      - run: yarn bootstrap
        name: Install inner package dependencies
        if: steps.lerna_cache.outputs.cache-hit != 'true'
      - run: yarn ${{ matrix.script }}
        name: Run ${{ matrix.script }} on inner packages code